# permissions for end users to view patches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: patch-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: reforma
    app.kubernetes.io/part-of: reforma
    app.kubernetes.io/managed-by: kustomize
  name: patch-viewer-role
rules:
- apiGroups:
  - reforma.prosimcorp.com
  resources:
  - patches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - reforma.prosimcorp.com
  resources:
  - patches/status
  verbs:
  - get
