# permissions for end users to view prepatches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: prepatch-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: reforma
    app.kubernetes.io/part-of: reforma
    app.kubernetes.io/managed-by: kustomize
  name: prepatch-viewer-role
rules:
- apiGroups:
  - reforma.prosimcorp.com
  resources:
  - prepatches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - reforma.prosimcorp.com
  resources:
  - prepatches/status
  verbs:
  - get
