apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: reforma
    app.kubernetes.io/instance: controller-manager-metrics-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: reforma
    app.kubernetes.io/part-of: reforma
    control-plane: reforma
  name: reforma-controller-manager-metrics-service
  namespace: reforma-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: reforma
    control-plane: reforma

