apiVersion: reforma.prosimcorp.com/v1alpha1
kind: Prepatch
metadata:
  labels:
    app.kubernetes.io/name: prepatch
    app.kubernetes.io/instance: prepatch-sample
    app.kubernetes.io/part-of: reforma
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: reforma
  name: prepatch-sample
spec:
  # TODO(user): Add fields here
