apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: reforma
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: reforma
    app.kubernetes.io/part-of: reforma
  name: reforma-leader-election-rolebinding
  namespace: reforma
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: reforma-leader-election-role
subjects:
- kind: ServiceAccount
  name: reforma-controller-manager
  namespace: reforma
